from flask import Flask, jsonify, request
app = Flask(__name__)
characters = [
    {"id": 1, "name": "Luke Skywalker", "species": "Human"},
    {"id": 2, "name": "Darth Vader", "species": "Human"},
    {"id": 3, "name": "Leia Organa", "species": "Human"},
    {"id": 4, "name": "Obi-Wan Kenobi", "species": "Human"},
    {"id": 5, "name": "Yoda", "species": "Unknown"},
    {"id": 6, "name": "R2-D2", "species": "Droid"},
    {"id": 7, "name": "C-3PO", "species": "Droid"},
    {"id": 8, "name": "Chewbacca", "species": "Wookiee"},
    {"id": 9, "name": "Han Solo", "species": "Human"},
    {"id": 10, "name": "Palpatine", "species": "Human"},
    {"id": 11, "name": "Mace Windu", "species": "Human"},
    {"id": 12, "name": "Anakin Skywalker", "species": "Human"},
    {"id": 13, "name": "Padmé Amidala", "species": "Human"},
    {"id": 14, "name": "Count Dooku", "species": "Human"},
    {"id": 15, "name": "Jango Fett", "species": "Human"},
    {"id": 16, "name": "Boba Fett", "species": "Human"},
    {"id": 17, "name": "Lando Calrissian", "species": "Human"},
    {"id": 18, "name": "Jabba the Hutt", "species": "Hutt"},
    {"id": 19, "name": "Ewok Elder Chirpa", "species": "Ewok"},
    {"id": 20, "name": "Wicket W. Warrick", "species": "Ewok"},
    {"id": 21, "name": "Admiral Ackbar", "species": "Mon Calamari"},
    {"id": 22, "name": "General Crix Madine", "species": "Human"},
    {"id": 23, "name": "Emperor's Royal Guard", "species": "Human"},
    {"id": 24, "name": "Nien Nunb", "species": "Sullustan"},
    {"id": 25, "name": "Lak Sivrak", "species": "Tracker"},
    {"id": 26, "name": "Wedge Antilles", "species": "Human"},
    {"id": 27, "name": "Biggs Darklighter", "species": "Human"},
    {"id": 28, "name": "Porkins", "species": "Human"},
    {"id": 29, "name": "Darth Maul", "species": "Zabrak"},
    {"id": 30, "name": "Qui-Gon Jinn", "species": "Human"},
    {"id": 31, "name": "Jar Jar Binks", "species": "Gungan"},
    {"id": 32, "name": "Boss Nass", "species": "Gungan"},
    {"id": 33, "name": "Admiral Ozzel", "species": "Human"},
    {"id": 34, "name": "General Veers", "species": "Human"},
    {"id": 35, "name": "Captain Needa", "species": "Human"},
    {"id": 36, "name": "Dengar", "species": "Human"},
    {"id": 37, "name": "IG-88", "species": "Droid"},
    {"id": 38, "name": "Bossk", "species": "Trandoshan"},
    {"id": 39, "name": "4-LOM", "species": "Droid"},
    {"id": 40, "name": "Aurra Sing", "species": "Human"},
    {"id": 41, "name": "Asajj Ventress", "species": "Dathomirian"},
    {"id": 42, "name": "General Grievous", "species": "Kaleesh"},
    {"id": 43, "name": "Savage Opress", "species": "Zabrak"},
    {"id": 44, "name": "Mother Talzin", "species": "Dathomirian"},
    {"id": 45, "name": "Barriss Offee", "species": "Mirialan"},
    {"id": 46, "name": "Stass Allie", "species": "Human"},
    {"id": 47, "name": "Agen Kolar", "species": "Zabraki"},
    {"id": 48, "name": "Saesee Tiin", "species": "Iktotchi"},
    {"id": 49, "name": "Kit Fisto", "species": "Nautolan"},
    {"id": 50, "name": "Plo Koon", "species": "Kel Dor"},
    {"id": 51, "name": "Aayla Secura", "species": "Twi'lek"},
    {"id": 52, "name": "Coleman Kcaj", "species": "Human"},
    {"id": 53, "name": "Depa Billaba", "species": "Chalactan"},
    {"id": 54, "name": "K'Kruhk", "species": "Whiphid"},
    {"id": 55, "name": "Jaro Tapal", "species": "Kel Dor"},
    {"id": 56, "name": "Sturn", "species": "Human"},
    {"id": 57, "name": "Jeth Markon", "species": "Human"},
    {"id": 58, "name": "Tiplar", "species": "Tiplarean"},
    {"id": 59, "name": "Tiplee", "species": "Tiplarean"},
    {"id": 60, "name": "Bol Chatak", "species": "Human"},
    {"id": 61, "name": "Jaro Sorick", "species": "Human"},
    {"id": 62, "name": "Jenna Zan Arbor", "species": "Human"},
    {"id": 63, "name": "Even Piell", "species": "Lannik"},
    {"id": 64, "name": "Micah Giiett", "species": "Human"},
    {"id": 65, "name": "Sora Bulq", "species": "Weequay"},
    {"id": 66, "name": "Ki-Adi-Mundi", "species": "Cerean"},
    {"id": 67, "name": "Yarael Poof", "species": "Quermian"},
    {"id": 68, "name": "Pablo-Jill", "species": "Kel Dor"},
    {"id": 69, "name": "Eeth Koth", "species": "Zabrak"},
    {"id": 70, "name": "Oppo Rancisis", "species": "Thisspiasian"},
    {"id": 71, "name": "Deewan", "species": "Human"},
    {"id": 72, "name": "Torr Snapt", "species": "Human"},
    {"id": 73, "name": "Jorus C'baoth", "species": "Human"},
    {"id": 74, "name": "Vilmarh Grahrk", "species": "Sakiyan"},
    {"id": 75, "name": "Vergere", "species": "Unknown"},
    {"id": 76, "name": "Marn Hierogryph", "species": "Gran"},
    {"id": 77, "name": "Zayne Carrick", "species": "Human"},
    {"id": 78, "name": "Bastila Shan", "species": "Human"},
    {"id": 79, "name": "Mission Vao", "species": "Twi'lek"},
    {"id": 80, "name": "Carth Onasi", "species": "Human"},
    {"id": 81, "name": "Canderous Ordo", "species": "Human"},
    {"id": 82, "name": "Revan", "species": "Human"},
    {"id": 83, "name": "HK-47", "species": "Droid"},
    {"id": 84, "name": "T3-M4", "species": "Droid"},
    {"id": 85, "name": "Big Z", "species": "Human"},
    {"id": 86, "name": "Juhani", "species": "Cathar"},
    {"id": 87, "name": "Belaya", "species": "Human"},
    {"id": 88, "name": "Kang", "species": "Human"},
    {"id": 89, "name": "Rickard Lussk", "species": "Human"},
    {"id": 90, "name": "Calo Nord", "species": "Human"},
    {"id": 91, "name": "Davik Kang", "species": "Human"},
    {"id": 92, "name": "Malak", "species": "Human"},
    {"id": 93, "name": "Rahasia", "species": "Human"},
    {"id": 94, "name": "Gadon Thek", "species": "Human"},
    {"id": 95, "name": "Sarna", "species": "Human"},
    {"id": 96, "name": "Vandar Tokare", "species": "Yoda Species"},
    {"id": 97, "name": "Masako Dane", "species": "Human"},
    {"id": 98, "name": "Yuthura Ban", "species": "Twi'lek"},
    {"id": 99, "name": "Uthar Wynn", "species": "Human"},
    {"id": 100, "name": "Shan Junix", "species": "Human"},
    {"id": 101, "name": "Trey Vizsla", "species": "Human"},
    {"id": 102, "name": "Din Djarin", "species": "Human"},
    {"id": 103, "name": "Grogu", "species": "Unknown"},
    {"id": 104, "name": "Greef Karga", "species": "Human"},
    {"id": 105, "name": "Cara Dune", "species": "Human"},
    {"id": 106, "name": "Kuiil", "species": "Ugnaught"},
    {"id": 107, "name": "IG-11", "species": "Droid"},
    {"id": 108, "name": "Moff Gideon", "species": "Human"},
    {"id": 109, "name": "Bo-Katan Wren", "species": "Human"},
    {"id": 110, "name": "Koska Reeves", "species": "Human"},
    {"id": 111, "name": "Axe Woves", "species": "Human"},
    {"id": 112, "name": "Peli Motto", "species": "Human"},
    {"id": 113, "name": "Fennec Shand", "species": "Human"},
    {"id": 114, "name": "Cad Bane", "species": "Duros"},
    {"id": 115, "name": "Bib Fortuna", "species": "Twi'lek"},
    {"id": 116, "name": "Lobot", "species": "Human"},
    {"id": 117, "name": "Ugnaught Foreman", "species": "Ugnaught"},
    {"id": 118, "name": "Captain Phasma", "species": "Human"},
    {"id": 119, "name": "Kylo Ren", "species": "Human"},
    {"id": 120, "name": "Rey", "species": "Human"},
    {"id": 121, "name": "Finn", "species": "Human"},
    {"id": 122, "name": "Poe Dameron", "species": "Human"},
    {"id": 123, "name": "BB-8", "species": "Droid"},
    {"id": 124, "name": "General Hux", "species": "Human"},
    {"id": 125, "name": "Starkiller Base Commander", "species": "Human"},
    {"id": 126, "name": "Captain Canady", "species": "Human"},
    {"id": 127, "name": "Jannah", "species": "Human"},
    {"id": 128, "name": "Zorii Bliss", "species": "Human"},
    {"id": 129, "name": "Babu Frik", "species": "Babu"},
    {"id": 130, "name": "Praetorian Guard 1", "species": "Human"},
    {"id": 131, "name": "Praetorian Guard 2", "species": "Human"},
    {"id": 132, "name": "Snap Wexley", "species": "Human"},
    {"id": 133, "name": "Rose Tico", "species": "Human"},
    {"id": 134, "name": "Paige Tico", "species": "Human"},
    {"id": 135, "name": "DJ", "species": "Human"},
    {"id": 136, "name": "Supreme Leader Snoke", "species": "Unknown"},
    {"id": 137, "name": "Amilyn Holdo", "species": "Human"},
    {"id": 138, "name": "Ben Solo", "species": "Human"},
    {"id": 139, "name": "D-O", "species": "Droid"},
    {"id": 140, "name": "4D-41", "species": "Droid"},
    {"id": 141, "name": "Maz Kanata", "species": "Unknown"},
    {"id": 142, "name": "Caretaker", "species": "Human"},
    {"id": 143, "name": "Admiral Piett", "species": "Human"},
    {"id": 144, "name": "Director Krennic", "species": "Human"},
    {"id": 145, "name": "Orson Krennic", "species": "Human"},
    {"id": 146, "name": "Jyn Erso", "species": "Human"},
    {"id": 147, "name": "Cassian Andor", "species": "Human"},
    {"id": 148, "name": "K-2SO", "species": "Droid"},
    {"id": 149, "name": "Chirrut Îmwe", "species": "Human"},
    {"id": 150, "name": "Baze Malbus", "species": "Human"},
    {"id": 151, "name": "Bodhi Rook", "species": "Human"},
    {"id": 152, "name": "Galen Erso", "species": "Human"},
    {"id": 153, "name": "Lyra Erso", "species": "Human"},
    {"id": 154, "name": "Saw Gerrera", "species": "Human"},
    {"id": 155, "name": "Governor Pryce", "species": "Human"},
    {"id": 156, "name": "Wilhuff Tarkin", "species": "Human"},
    {"id": 157, "name": "Tobias Beckett", "species": "Human"},
    {"id": 158, "name": "Val Beckett", "species": "Human"},
    {"id": 159, "name": "Enfys Nest", "species": "Human"},
    {"id": 160, "name": "Lando Calrissian Young", "species": "Human"},
    {"id": 161, "name": "L3-37", "species": "Droid"},
    {"id": 162, "name": "Rio Durant", "species": "Ardennian"},
    {"id": 163, "name": "Dryden Vos", "species": "Human"},
    {"id": 164, "name": "Lady Proxima", "species": "Unknown"},
    {"id": 165, "name": "Watto", "species": "Toydarian"},
    {"id": 166, "name": "Sebulba", "species": "Dug"},
    {"id": 167, "name": "Mos Eisley Cantina Patron 1", "species": "Aqualish"},
    {"id": 168, "name": "Mos Eisley Cantina Patron 2", "species": "Rodian"},
    {"id": 169, "name": "Mos Eisley Cantina Patron 3", "species": "Twi'lek"},
    {"id": 170, "name": "Tatooine Moisture Farmer", "species": "Human"},
    {"id": 171, "name": "Death Star Technician", "species": "Human"},
    {"id": 172, "name": "Death Star Officer", "species": "Human"},
    {"id": 173, "name": "Destroyer Droid", "species": "Droid"},
    {"id": 174, "name": "Super Battle Droid", "species": "Droid"},
    {"id": 175, "name": "Droideka", "species": "Droid"},
    {"id": 176, "name": "B1 Battle Droid", "species": "Droid"},
    {"id": 177, "name": "B2 Super Battle Droid", "species": "Droid"},
    {"id": 178, "name": "Commando Droid", "species": "Droid"},
    {"id": 179, "name": "Geonosian Warrior", "species": "Geonosian"},
    {"id": 180, "name": "Geonosian Queen", "species": "Geonosian"},
    {"id": 181, "name": "Tusken Raider", "species": "Tusken"},
    {"id": 182, "name": "Tusken Raider Chief", "species": "Tusken"},
    {"id": 183, "name": "Wampa", "species": "Wampa"},
    {"id": 184, "name": "Rancor Keeper", "species": "Human"},
    {"id": 185, "name": "Tauntaun Handler", "species": "Human"},
    {"id": 186, "name": "AT-AT Pilot", "species": "Human"},
    {"id": 187, "name": "AT-ST Pilot", "species": "Human"},
    {"id": 188, "name": "TIE Fighter Pilot 1", "species": "Human"},
    {"id": 189, "name": "TIE Fighter Pilot 2", "species": "Human"},
    {"id": 190, "name": "TIE Interceptor Pilot", "species": "Human"},
    {"id": 191, "name": "TIE Bomber Pilot", "species": "Human"},
    {"id": 192, "name": "Lambda Shuttle Pilot", "species": "Human"},
    {"id": 193, "name": "X-Wing Pilot Wedge", "species": "Human"},
    {"id": 194, "name": "X-Wing Pilot Biggs", "species": "Human"},
    {"id": 195, "name": "Y-Wing Pilot", "species": "Human"},
    {"id": 196, "name": "A-Wing Pilot", "species": "Human"},
    {"id": 197, "name": "Snowspeeder Pilot", "species": "Human"},
    {"id": 198, "name": "Landspeeder Driver", "species": "Human"},
    {"id": 199, "name": "Speeder Bike Scout Trooper", "species": "Human"},
    {"id": 200, "name": "Blaster Specialist", "species": "Human"},
    {"id": 201, "name": "Force Sensitive Child", "species": "Human"},
    {"id": 202, "name": "Clone Trooper Captain", "species": "Human"},
    {"id": 203, "name": "Clone Trooper Commander", "species": "Human"},
    {"id": 204, "name": "Battle Droid Commander", "species": "Droid"},
    {"id": 205, "name": "Battle Droid Pilot", "species": "Droid"},
    {"id": 206, "name": "Pit Droid 1", "species": "Droid"},
    {"id": 207, "name": "Pit Droid 2", "species": "Droid"},
    {"id": 208, "name": "Protocol Droid", "species": "Droid"},
    {"id": 209, "name": "Astromech Droid R5-D4", "species": "Droid"},
]

@app.route("/")
def home():
    return jsonify({
        "message": "Star Wars Mini API",
        "endpoints": [
            "/api/people",
            "/api/people?limit=5",
            "/api/people?limit=50 (max)"
        ],
        "total_characters": len(characters)
    })

@app.route("/api/people")
def get_people():
    limit = request.args.get("limit", default=10, type=int)
    
    # Cap the limit at 50
    if limit > 50:
        limit = 50
    
    return jsonify({
        "count": min(limit, len(characters)),
        "limit": limit,
        "total": len(characters),
        "results": characters[:limit]
    })

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000)